language: rust

rust: nightly

cache: cargo

script: scripts/travis_build.sh

before_script:
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y
  - source ~/.cargo/env
  - rustup component add rust-src
  - (cargo install xargo || true)
  #- PATH=$PATH:~/.cargo/bin

addons:
  apt:
    packages:
      - cmake
      - libssl-dev
    sources:
      - kalakris-cmake
