language: rust

rust:
  - nightly-2016-08-18
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script: scripts/travis_build.sh

before_script:
  - cargo install xargo

addons:
  apt:
    packages:
    - cmake
    - libssl-dev
