language: rust

rust: nightly

cache: cargo

script: 
  - scripts/travis_build.sh
  - scripts/travis_pr.sh

before_script:
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y
  - source ~/.cargo/env
  - rustup component add rust-src
  - (test -x $HOME/.cargo/bin/xargo || cargo install xargo)
  - (test $(cargo fmt --version | grep nightly | wc -l) -eq 1 || cargo install rustfmt-nightly)
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - cargo install-update -a

addons:
  apt:
    packages:
      - cmake
      - libssl-dev
    sources:
      - kalakris-cmake
