language: rust

rust:
  - nightly-2016-08-18
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script: scripts/travis_build.sh

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake libssl-dev
