language: rust

rust: nightly

cache: cargo

script: scripts/travis_build.sh

before_script:
  - (cargo install xargo || true)
  - PATH=$PATH:~/.cargo/bin

addons:
  apt:
    packages:
      - cmake
      - libssl-dev
    sources:
      - kalakris-cmake
